name: Run Tests

on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: ci
        run: |
          npm ci
      - name: test
        run: |
          npm run test
      - name: build
        run: |
          git clean -fdx dist src && npm run build
